<?php

namespace Parallel\Compliance\Mappings;

use Parallel\Compliance\Capabilities\CommonCapability;
use Parallel\Compliance\Frameworks\GdprRequirement;
use Parallel\Compliance\Frameworks\OwaspRequirement;
use Parallel\Compliance\Frameworks\Soc2TrustServicesCriteria;
use Parallel\Compliance\Frameworks\VantaControl;

class CapabilityFrameworkMappings
{
    /**
     * @return array<string, array<int, mixed>>
     */
    public static function defaults(): array
    {
        return [
            CommonCapability::UserDataErasure->value => [
                GdprRequirement::Article17,
                GdprRequirement::Article19,
                OwaspRequirement::AsvsDataProtection,
                Soc2TrustServicesCriteria::C1_2,
                Soc2TrustServicesCriteria::CC6_5,
                Soc2TrustServicesCriteria::P4_3,
                VantaControl::AST_1,
                VantaControl::AST_2,
                VantaControl::DCH_1,
                VantaControl::DCH_6,
                VantaControl::DCH_10,
            ],
            CommonCapability::UserDataExport->value => [
                GdprRequirement::Article15,
                GdprRequirement::Article20,
                OwaspRequirement::AsvsDataProtection,
                Soc2TrustServicesCriteria::P5_1,
                Soc2TrustServicesCriteria::P6_7,
                VantaControl::DCH_8,
                VantaControl::DCH_9,
                VantaControl::IRO_4,
            ],
            CommonCapability::UserDataAccess->value => [
                GdprRequirement::Article12,
                GdprRequirement::Article15,
                OwaspRequirement::AsvsDataProtection,
                Soc2TrustServicesCriteria::P5_1,
                Soc2TrustServicesCriteria::P6_7,
                VantaControl::DCH_8,
                VantaControl::DCH_9,
                VantaControl::PRI_15,
            ],
            CommonCapability::UserDataRectification->value => [
                GdprRequirement::Article16,
                GdprRequirement::Article19,
                Soc2TrustServicesCriteria::P5_2,
                Soc2TrustServicesCriteria::P7_1,
                VantaControl::DCH_7,
                VantaControl::PRI_2,
                VantaControl::PRI_15,
            ],
            CommonCapability::UserDataRestriction->value => [
                GdprRequirement::Article18,
                GdprRequirement::Article19,
                Soc2TrustServicesCriteria::P4_1,
                Soc2TrustServicesCriteria::P4_2,
                Soc2TrustServicesCriteria::P5_1,
                VantaControl::AST_2,
                VantaControl::DCH_5,
                VantaControl::PRI_13,
            ],
            CommonCapability::UserDataObjection->value => [
                GdprRequirement::Article21,
                Soc2TrustServicesCriteria::P2_1,
                Soc2TrustServicesCriteria::P4_1,
                VantaControl::PRI_12,
                VantaControl::PRI_13,
            ],
            CommonCapability::DataRetention->value => [
                GdprRequirement::Article5,
                GdprRequirement::Article25,
                GdprRequirement::Article30,
                OwaspRequirement::AsvsDataProtection,
                Soc2TrustServicesCriteria::CC5_3,
                Soc2TrustServicesCriteria::CC6_5,
                Soc2TrustServicesCriteria::C1_2,
                Soc2TrustServicesCriteria::P4_2,
                Soc2TrustServicesCriteria::P4_3,
                VantaControl::AST_2,
                VantaControl::DCH_1,
                VantaControl::PRI_8,
            ],
            CommonCapability::DataMinimization->value => [
                GdprRequirement::Article5,
                GdprRequirement::Article25,
                OwaspRequirement::AsvsDataProtection,
                Soc2TrustServicesCriteria::P3_1,
                Soc2TrustServicesCriteria::P4_1,
                VantaControl::PRI_4,
                VantaControl::PRI_13,
            ],
            CommonCapability::PurposeLimitation->value => [
                GdprRequirement::Article5,
                GdprRequirement::Article6,
                GdprRequirement::Article13,
                GdprRequirement::Article14,
                Soc2TrustServicesCriteria::P1_1,
                Soc2TrustServicesCriteria::P2_1,
                Soc2TrustServicesCriteria::P4_1,
                VantaControl::PRI_6,
                VantaControl::PRI_13,
            ],
            CommonCapability::ConsentCapture->value => [
                GdprRequirement::Article6,
                GdprRequirement::Article7,
                GdprRequirement::Article25,
                Soc2TrustServicesCriteria::P2_1,
                Soc2TrustServicesCriteria::P3_2,
                VantaControl::PRI_9,
                VantaControl::PRI_10,
                VantaControl::PRI_11,
            ],
            CommonCapability::ConsentWithdrawal->value => [
                GdprRequirement::Article7,
                GdprRequirement::Article17,
                GdprRequirement::Article21,
                Soc2TrustServicesCriteria::P2_1,
                Soc2TrustServicesCriteria::P4_1,
                VantaControl::PRI_12,
            ],
            CommonCapability::PrivacyNotice->value => [
                GdprRequirement::Article12,
                GdprRequirement::Article13,
                GdprRequirement::Article14,
                Soc2TrustServicesCriteria::P1_1,
                VantaControl::PRI_3,
                VantaControl::PRI_6,
                VantaControl::PRI_14,
                VantaControl::PRI_16,
            ],
            CommonCapability::ProcessingRecords->value => [
                GdprRequirement::Article30,
                Soc2TrustServicesCriteria::CC2_1,
                Soc2TrustServicesCriteria::P6_2,
                Soc2TrustServicesCriteria::P6_7,
                Soc2TrustServicesCriteria::P8_1,
                VantaControl::IRO_4,
                VantaControl::PRI_1,
                VantaControl::PRI_17,
            ],
            CommonCapability::ProcessorManagement->value => [
                GdprRequirement::Article28,
                GdprRequirement::Article32,
                Soc2TrustServicesCriteria::CC3_2,
                Soc2TrustServicesCriteria::CC9_2,
                Soc2TrustServicesCriteria::P6_1,
                Soc2TrustServicesCriteria::P6_4,
                Soc2TrustServicesCriteria::P6_5,
                VantaControl::PRI_17,
                VantaControl::TPM_1,
                VantaControl::TPM_2,
            ],
            CommonCapability::PrivacyImpactAssessment->value => [
                GdprRequirement::Article24,
                GdprRequirement::Article25,
                GdprRequirement::Article35,
                Soc2TrustServicesCriteria::CC3_1,
                Soc2TrustServicesCriteria::CC3_2,
                Soc2TrustServicesCriteria::CC3_3,
                Soc2TrustServicesCriteria::CC3_4,
                Soc2TrustServicesCriteria::CC4_1,
                Soc2TrustServicesCriteria::CC4_2,
                Soc2TrustServicesCriteria::P8_1,
                VantaControl::IAO_1,
                VantaControl::RSK_2,
                VantaControl::RSK_3,
            ],
            CommonCapability::BreachNotification->value => [
                GdprRequirement::Article33,
                GdprRequirement::Article34,
                Soc2TrustServicesCriteria::CC7_3,
                Soc2TrustServicesCriteria::CC7_4,
                Soc2TrustServicesCriteria::P6_3,
                Soc2TrustServicesCriteria::P6_6,
                VantaControl::IRO_2,
                VantaControl::IRO_3,
            ],
            CommonCapability::AccessLogging->value => [
                GdprRequirement::Article30,
                GdprRequirement::Article32,
                OwaspRequirement::AsvsErrorLogging,
                OwaspRequirement::WstgErrorHandling,
                Soc2TrustServicesCriteria::CC2_1,
                Soc2TrustServicesCriteria::CC7_2,
                Soc2TrustServicesCriteria::PI1_2,
                Soc2TrustServicesCriteria::PI1_3,
                VantaControl::MON_2,
                VantaControl::TDA_3,
            ],
            CommonCapability::Authentication->value => [
                GdprRequirement::Article32,
                OwaspRequirement::AsvsAuthentication,
                OwaspRequirement::WstgAuthentication,
                Soc2TrustServicesCriteria::CC6_1,
                Soc2TrustServicesCriteria::CC6_2,
                Soc2TrustServicesCriteria::CC6_3,
                VantaControl::CRY_5,
                VantaControl::IAC_11,
                VantaControl::IAC_12,
            ],
            CommonCapability::Authorization->value => [
                GdprRequirement::Article25,
                GdprRequirement::Article32,
                OwaspRequirement::AsvsAccessControl,
                OwaspRequirement::WstgAuthorization,
                Soc2TrustServicesCriteria::CC6_1,
                Soc2TrustServicesCriteria::CC6_2,
                Soc2TrustServicesCriteria::CC6_3,
                VantaControl::IAC_1,
                VantaControl::IAC_2,
                VantaControl::IAC_7,
                VantaControl::IAC_9,
            ],
            CommonCapability::SessionManagement->value => [
                GdprRequirement::Article32,
                OwaspRequirement::AsvsSessionManagement,
                OwaspRequirement::WstgSessionManagement,
                Soc2TrustServicesCriteria::CC6_1,
                Soc2TrustServicesCriteria::CC6_6,
                VantaControl::CRY_5,
                VantaControl::IAC_12,
            ],
            CommonCapability::InputValidation->value => [
                OwaspRequirement::AsvsInputValidation,
                OwaspRequirement::WstgInputValidation,
                Soc2TrustServicesCriteria::CC7_1,
                Soc2TrustServicesCriteria::PI1_2,
                Soc2TrustServicesCriteria::PI1_3,
                VantaControl::MON_3,
                VantaControl::TDA_4,
            ],
            CommonCapability::OutputEncoding->value => [
                OwaspRequirement::AsvsInputValidation,
                OwaspRequirement::WstgClientSide,
                Soc2TrustServicesCriteria::CC7_1,
                Soc2TrustServicesCriteria::PI1_4,
                VantaControl::TDA_2,
            ],
            CommonCapability::SecureConfiguration->value => [
                GdprRequirement::Article25,
                GdprRequirement::Article32,
                OwaspRequirement::AsvsConfiguration,
                OwaspRequirement::WstgConfiguration,
                Soc2TrustServicesCriteria::CC3_4,
                Soc2TrustServicesCriteria::CC5_2,
                Soc2TrustServicesCriteria::CC7_1,
                Soc2TrustServicesCriteria::CC8_1,
                VantaControl::CFG_1,
                VantaControl::CHG_1,
                VantaControl::NET_5,
            ],
            CommonCapability::SecretsManagement->value => [
                GdprRequirement::Article32,
                OwaspRequirement::AsvsCryptography,
                OwaspRequirement::AsvsConfiguration,
                Soc2TrustServicesCriteria::CC6_1,
                Soc2TrustServicesCriteria::CC6_7,
                Soc2TrustServicesCriteria::C1_1,
                VantaControl::CRY_2,
                VantaControl::CRY_4,
            ],
            CommonCapability::DependencyManagement->value => [
                OwaspRequirement::AsvsMaliciousCode,
                OwaspRequirement::AsvsConfiguration,
                Soc2TrustServicesCriteria::CC6_8,
                Soc2TrustServicesCriteria::CC7_1,
                Soc2TrustServicesCriteria::CC8_1,
                Soc2TrustServicesCriteria::CC9_1,
                VantaControl::CHG_3,
                VantaControl::VPM_1,
                VantaControl::VPM_2,
            ],
            CommonCapability::SecurityMonitoring->value => [
                GdprRequirement::Article32,
                OwaspRequirement::AsvsErrorLogging,
                OwaspRequirement::WstgErrorHandling,
                Soc2TrustServicesCriteria::CC4_1,
                Soc2TrustServicesCriteria::CC4_2,
                Soc2TrustServicesCriteria::CC7_1,
                Soc2TrustServicesCriteria::CC7_2,
                Soc2TrustServicesCriteria::CC7_3,
                VantaControl::MON_1,
                VantaControl::MON_2,
                VantaControl::MON_4,
                VantaControl::OPS_1,
            ],
            CommonCapability::IncidentResponse->value => [
                GdprRequirement::Article33,
                GdprRequirement::Article34,
                Soc2TrustServicesCriteria::CC7_3,
                Soc2TrustServicesCriteria::CC7_4,
                Soc2TrustServicesCriteria::CC7_5,
                Soc2TrustServicesCriteria::CC9_1,
                Soc2TrustServicesCriteria::P6_3,
                Soc2TrustServicesCriteria::P6_6,
                VantaControl::IRO_1,
                VantaControl::IRO_2,
                VantaControl::IRO_3,
            ],
            CommonCapability::ChangeManagement->value => [
                GdprRequirement::Article24,
                GdprRequirement::Article25,
                OwaspRequirement::AsvsArchitecture,
                Soc2TrustServicesCriteria::CC3_4,
                Soc2TrustServicesCriteria::CC5_2,
                Soc2TrustServicesCriteria::CC8_1,
                VantaControl::CHG_1,
                VantaControl::CHG_2,
                VantaControl::CHG_3,
            ],
            CommonCapability::EncryptionAtRest->value => [
                GdprRequirement::Article32,
                OwaspRequirement::AsvsCryptography,
                OwaspRequirement::AsvsDataProtection,
                OwaspRequirement::WstgCryptography,
                Soc2TrustServicesCriteria::CC6_1,
                Soc2TrustServicesCriteria::C1_1,
                Soc2TrustServicesCriteria::PI1_4,
                VantaControl::CRY_4,
            ],
            CommonCapability::EncryptionInTransit->value => [
                GdprRequirement::Article32,
                OwaspRequirement::AsvsCommunications,
                OwaspRequirement::WstgCryptography,
                Soc2TrustServicesCriteria::CC6_7,
                Soc2TrustServicesCriteria::C1_1,
                VantaControl::CRY_3,
                VantaControl::NET_1,
            ],
        ];
    }
}
