<?php

namespace Parallel\Compliance\Controls;

use Parallel\Compliance\Data\ControlRecord;
use Parallel\Compliance\Data\VantaComplianceData;

/**
 * @generated by security:generate-vanta-data
 */
enum VantaControl: string implements Control
{
    /**
     * Asset disposal procedures utilized
     *
     * The company has electronic media containing confidential information purged or destroyed in accordance with best practices, and certificates of destruction are issued for each device destroyed.
     */
    case AST_1 = 'VANTA:AST-1';

    /**
     * Data retention procedures established
     *
     * The company has formal retention and disposal procedures in place to guide the secure retention and disposal of company and customer data.
     */
    case AST_2 = 'VANTA:AST-2';

    /**
     * Production inventory maintained
     *
     * The company maintains a formal inventory of production system assets.
     */
    case AST_3 = 'VANTA:AST-3';

    /**
     * Continuity and Disaster Recovery plans established
     *
     * The company has Business Continuity and Disaster Recovery Plans in place that outline communication plans in order to maintain information security continuity in the event of the unavailability of key personnel.
     */
    case BCD_1 = 'VANTA:BCD-1';

    /**
     * Continuity and Disaster Recovery plans tested
     *
     * The company has a documented Business Continuity/Disaster Recovery (BC/DR) plan and tests it at least annually.
     */
    case BCD_2 = 'VANTA:BCD-2';

    /**
     * Configuration management system established
     *
     * The company has a configuration management procedure in place to ensure that system configurations are deployed consistently throughout the environment.
     */
    case CFG_1 = 'VANTA:CFG-1';

    /**
     * Change management procedures enforced
     *
     * The company requires changes to software and infrastructure components of the service to be authorized, formally documented, tested, reviewed, and approved prior to being implemented in the production environment.
     */
    case CHG_1 = 'VANTA:CHG-1';

    /**
     * Production deployment access restricted
     *
     * The company restricts access to migrate changes to production to authorized personnel.
     */
    case CHG_2 = 'VANTA:CHG-2';

    /**
     * Development lifecycle established
     *
     * The company has a formal systems development life cycle (SDLC) methodology in place that governs the development, acquisition, implementation, changes (including emergency changes), and maintenance of information systems and related technology requirements.
     */
    case CHG_3 = 'VANTA:CHG-3';

    /**
     * Unique production database authentication enforced
     *
     * The company requires authentication to production datastores to use authorized secure authentication mechanisms, such as unique SSH key.
     */
    case CRY_1 = 'VANTA:CRY-1';

    /**
     * Encryption key access restricted
     *
     * The company restricts privileged access to encryption keys to authorized users with a business need.
     */
    case CRY_2 = 'VANTA:CRY-2';

    /**
     * Portable media encrypted
     *
     * The company encrypts portable and removable media devices when used.
     */
    case CRY_3 = 'VANTA:CRY-3';

    /**
     * Data encryption utilized
     *
     * The company's datastores housing sensitive customer data are encrypted at rest.
     */
    case CRY_4 = 'VANTA:CRY-4';

    /**
     * Unique account authentication enforced
     *
     * The company requires authentication to systems and applications to use unique username and password or authorized Secure Socket Shell (SSH) keys.
     */
    case CRY_5 = 'VANTA:CRY-5';

    /**
     * Customer data deleted upon leaving
     *
     * The company purges or removes customer data containing confidential information from the application environment, in accordance with best practices, when customers leave the service.
     */
    case DCH_1 = 'VANTA:DCH-1';

    /**
     * Data classification policy established
     *
     * The company has a data classification policy in place to help ensure that confidential data is properly secured and restricted to authorized personnel.
     */
    case DCH_5 = 'VANTA:DCH-5';

    /**
     * Anti-malware technology utilized
     *
     * The company deploys anti-malware technology to environments commonly susceptible to malicious attacks and configures this to be updated routinely, logged, and installed on all relevant systems.
     */
    case END_1 = 'VANTA:END-1';

    /**
     * Production application access restricted
     *
     * System access restricted to authorized access only
     */
    case IAC_1 = 'VANTA:IAC-1';

    /**
     * Unique network system authentication enforced
     *
     * The company requires authentication to the "production network" to use unique usernames and passwords or authorized Secure Socket Shell (SSH) keys.
     */
    case IAC_10 = 'VANTA:IAC-10';

    /**
     * Password policy enforced
     *
     * The company requires passwords for in-scope system components to be configured according to the company's policy.
     */
    case IAC_11 = 'VANTA:IAC-11';

    /**
     * Remote access MFA enforced
     *
     * The company's production systems can only be remotely accessed by authorized employees possessing a valid multi-factor authentication (MFA) method.
     */
    case IAC_12 = 'VANTA:IAC-12';

    /**
     * Remote access encrypted enforced
     *
     * The company's production systems can only be remotely accessed by authorized employees via an approved encrypted connection.
     */
    case IAC_13 = 'VANTA:IAC-13';

    /**
     * Access control procedures established
     *
     * The company's access control policy documents the requirements for the following access control functions:
     *
     * - adding new users;
     *
     * - modifying users; and/or
     *
     * - removing an existing user's access.
     */
    case IAC_2 = 'VANTA:IAC-2';

    /**
     * Production database access restricted
     *
     * The company restricts privileged access to databases to authorized users with a business need.
     */
    case IAC_3 = 'VANTA:IAC-3';

    /**
     * Firewall access restricted
     *
     * The company restricts privileged access to the firewall to authorized users with a business need.
     */
    case IAC_4 = 'VANTA:IAC-4';

    /**
     * Production OS access restricted
     *
     * The company restricts privileged access to the operating system to authorized users with a business need.
     */
    case IAC_5 = 'VANTA:IAC-5';

    /**
     * Production network access restricted
     *
     * The company restricts privileged access to the production network to authorized users with a business need.
     */
    case IAC_6 = 'VANTA:IAC-6';

    /**
     * Access reviews conducted
     *
     * The company conducts access reviews at least quarterly for the in-scope system components to help ensure that access is restricted appropriately. Required changes are tracked to completion.
     */
    case IAC_7 = 'VANTA:IAC-7';

    /**
     * Access revoked upon termination
     *
     * The company completes termination checklists to ensure that access is revoked for terminated employees within SLAs.
     */
    case IAC_8 = 'VANTA:IAC-8';

    /**
     * Access requests required
     *
     * The company ensures that user access to in-scope system components is based on job role and function or requires a documented access request form and manager approval prior to access being provisioned.
     */
    case IAC_9 = 'VANTA:IAC-9';

    /**
     * Control self-assessments conducted
     *
     * The company performs control self-assessments at least annually to gain assurance that controls are in place and operating effectively. Corrective actions are taken based on relevant findings. If the company has committed to an SLA for a finding, the corrective action is completed within that SLA.
     */
    case IAO_1 = 'VANTA:IAO-1';

    /**
     * Penetration testing performed
     *
     * The company's penetration testing is performed at least annually. A remediation plan is developed and changes are implemented to remediate vulnerabilities in accordance with SLAs.
     */
    case IAO_2 = 'VANTA:IAO-2';

    /**
     * Incident response plan tested
     *
     * The company tests their incident response plan at least annually.
     */
    case IRO_1 = 'VANTA:IRO-1';

    /**
     * Incident response policies established
     *
     * The company has security and privacy incident response policies and procedures that are documented and communicated to authorized users.
     */
    case IRO_2 = 'VANTA:IRO-2';

    /**
     * Incident management procedures followed
     *
     * The company's security and privacy incidents are logged, tracked, resolved, and communicated to affected or relevant parties by management according to the company's security incident response policy and procedures.
     */
    case IRO_3 = 'VANTA:IRO-3';

    /**
     * MDM system utilized
     *
     * The company has a mobile device management (MDM) system in place to centrally manage mobile devices supporting the service.
     */
    case MDM_1 = 'VANTA:MDM-1';

    /**
     * Intrusion detection system utilized
     *
     * The company uses an intrusion detection system to provide continuous monitoring of the company's network and early detection of potential security breaches.
     */
    case MON_1 = 'VANTA:MON-1';

    /**
     * Log management utilized
     *
     * The company utilizes a log management tool to identify events that may have a potential impact on the company's ability to achieve its security objectives.
     */
    case MON_2 = 'VANTA:MON-2';

    /**
     * Infrastructure performance monitored
     *
     * An infrastructure monitoring tool is utilized to monitor systems, infrastructure, and performance and generates alerts when specific predefined thresholds are met.
     */
    case MON_4 = 'VANTA:MON-4';

    /**
     * Data transmission encrypted
     *
     * The company uses secure data transmission protocols to encrypt confidential and sensitive data when transmitted over public networks.
     */
    case NET_1 = 'VANTA:NET-1';

    /**
     * Network segmentation implemented
     *
     * The company's network is segmented to prevent unauthorized access to customer data.
     */
    case NET_2 = 'VANTA:NET-2';

    /**
     * Network firewalls reviewed
     *
     * The company reviews its firewall rulesets at least annually. Required changes are tracked to completion.
     */
    case NET_3 = 'VANTA:NET-3';

    /**
     * Network firewalls utilized
     *
     * The company uses firewalls and configures them to prevent unauthorized access.
     */
    case NET_4 = 'VANTA:NET-4';

    /**
     * Network and system hardening standards maintained
     *
     * The company's network and system hardening standards are documented, based on industry best practices, and reviewed at least annually.
     */
    case NET_5 = 'VANTA:NET-5';

    /**
     * Vulnerability and system monitoring procedures established
     *
     * The company's formal policies outline the requirements for the following functions related to IT / Engineering:
     *
     * - vulnerability management;
     *
     * - system monitoring.
     */
    case OPS_1 = 'VANTA:OPS-1';

    /**
     * Third-party agreements established
     *
     * The company has written agreements in place with vendors and related third-parties. These agreements include confidentiality and privacy commitments applicable to that entity.
     */
    case TPM_1 = 'VANTA:TPM-1';

    /**
     * Vendor management program established
     *
     * The company has a vendor management program in place. Components of this program include:
     *
     * - critical third-party vendor inventory;
     *
     * - vendor's security and privacy requirements; and
     *
     * - review of critical third-party vendors at least annually.
     */
    case TPM_2 = 'VANTA:TPM-2';

    /**
     * Service infrastructure maintained
     *
     * The company has infrastructure supporting the service patched as a part of routine maintenance and as a result of identified vulnerabilities to help ensure that servers supporting the service are hardened against security threats.
     */
    case VPM_1 = 'VANTA:VPM-1';

    /**
     * Vulnerabilities scanned and remediated
     *
     * Host-based vulnerability scans are performed at least quarterly on all external-facing systems. Critical and high vulnerabilities are tracked to remediation.
     */
    case VPM_2 = 'VANTA:VPM-2';

    public function id(): string
    {
        return $this->value;
    }

    public function source(): string
    {
        return $this->record()->source;
    }

    public function externalId(): string
    {
        return str_replace('VANTA:', '', $this->value);
    }

    public function slug(): string
    {
        return $this->record()->vantaId;
    }

    public function title(): string
    {
        return $this->record()->name;
    }

    public function description(): ?string
    {
        return $this->record()->description;
    }

    public function domains(): array
    {
        return $this->record()->domains;
    }

    private function record(): ControlRecord
    {
        $record = VantaComplianceData::fromPackageResources()->control($this);

        if (! $record) {
            throw new \RuntimeException("Missing Vanta control data for {$this->value}.");
        }

        return $record;
    }
}
