<?php

namespace Parallel\Compliance\Controls;

enum VantaControl: string implements Control
{
    case AST_1 = 'VANTA:AST-1';
    case AST_2 = 'VANTA:AST-2';
    case AST_3 = 'VANTA:AST-3';
    case BCD_1 = 'VANTA:BCD-1';
    case BCD_2 = 'VANTA:BCD-2';
    case BCD_3 = 'VANTA:BCD-3';
    case BCD_4 = 'VANTA:BCD-4';
    case BCD_5 = 'VANTA:BCD-5';
    case BCD_6 = 'VANTA:BCD-6';
    case CAP_1 = 'VANTA:CAP-1';
    case CFG_1 = 'VANTA:CFG-1';
    case CHG_1 = 'VANTA:CHG-1';
    case CHG_2 = 'VANTA:CHG-2';
    case CHG_3 = 'VANTA:CHG-3';
    case CPL_1 = 'VANTA:CPL-1';
    case CPL_2 = 'VANTA:CPL-2';
    case CRY_1 = 'VANTA:CRY-1';
    case CRY_2 = 'VANTA:CRY-2';
    case CRY_3 = 'VANTA:CRY-3';
    case CRY_4 = 'VANTA:CRY-4';
    case CRY_5 = 'VANTA:CRY-5';
    case DCH_1 = 'VANTA:DCH-1';
    case DCH_10 = 'VANTA:DCH-10';
    case DCH_11 = 'VANTA:DCH-11';
    case DCH_2 = 'VANTA:DCH-2';
    case DCH_3 = 'VANTA:DCH-3';
    case DCH_4 = 'VANTA:DCH-4';
    case DCH_5 = 'VANTA:DCH-5';
    case DCH_6 = 'VANTA:DCH-6';
    case DCH_7 = 'VANTA:DCH-7';
    case DCH_8 = 'VANTA:DCH-8';
    case DCH_9 = 'VANTA:DCH-9';
    case END_1 = 'VANTA:END-1';
    case GOV_1 = 'VANTA:GOV-1';
    case GOV_10 = 'VANTA:GOV-10';
    case GOV_11 = 'VANTA:GOV-11';
    case GOV_12 = 'VANTA:GOV-12';
    case GOV_13 = 'VANTA:GOV-13';
    case GOV_2 = 'VANTA:GOV-2';
    case GOV_3 = 'VANTA:GOV-3';
    case GOV_4 = 'VANTA:GOV-4';
    case GOV_5 = 'VANTA:GOV-5';
    case GOV_6 = 'VANTA:GOV-6';
    case GOV_7 = 'VANTA:GOV-7';
    case GOV_8 = 'VANTA:GOV-8';
    case GOV_9 = 'VANTA:GOV-9';
    case HRS_1 = 'VANTA:HRS-1';
    case HRS_2 = 'VANTA:HRS-2';
    case HRS_3 = 'VANTA:HRS-3';
    case HRS_4 = 'VANTA:HRS-4';
    case HRS_5 = 'VANTA:HRS-5';
    case HRS_6 = 'VANTA:HRS-6';
    case IAC_1 = 'VANTA:IAC-1';
    case IAC_10 = 'VANTA:IAC-10';
    case IAC_11 = 'VANTA:IAC-11';
    case IAC_12 = 'VANTA:IAC-12';
    case IAC_13 = 'VANTA:IAC-13';
    case IAC_2 = 'VANTA:IAC-2';
    case IAC_3 = 'VANTA:IAC-3';
    case IAC_4 = 'VANTA:IAC-4';
    case IAC_5 = 'VANTA:IAC-5';
    case IAC_6 = 'VANTA:IAC-6';
    case IAC_7 = 'VANTA:IAC-7';
    case IAC_8 = 'VANTA:IAC-8';
    case IAC_9 = 'VANTA:IAC-9';
    case IAO_1 = 'VANTA:IAO-1';
    case IAO_2 = 'VANTA:IAO-2';
    case IRO_1 = 'VANTA:IRO-1';
    case IRO_2 = 'VANTA:IRO-2';
    case IRO_3 = 'VANTA:IRO-3';
    case IRO_4 = 'VANTA:IRO-4';
    case MDM_1 = 'VANTA:MDM-1';
    case MON_1 = 'VANTA:MON-1';
    case MON_2 = 'VANTA:MON-2';
    case MON_3 = 'VANTA:MON-3';
    case MON_4 = 'VANTA:MON-4';
    case NET_1 = 'VANTA:NET-1';
    case NET_2 = 'VANTA:NET-2';
    case NET_3 = 'VANTA:NET-3';
    case NET_4 = 'VANTA:NET-4';
    case NET_5 = 'VANTA:NET-5';
    case OPS_1 = 'VANTA:OPS-1';
    case PES_1 = 'VANTA:PES-1';
    case PES_2 = 'VANTA:PES-2';
    case PES_3 = 'VANTA:PES-3';
    case PES_4 = 'VANTA:PES-4';
    case PES_5 = 'VANTA:PES-5';
    case PRI_1 = 'VANTA:PRI-1';
    case PRI_10 = 'VANTA:PRI-10';
    case PRI_11 = 'VANTA:PRI-11';
    case PRI_12 = 'VANTA:PRI-12';
    case PRI_13 = 'VANTA:PRI-13';
    case PRI_14 = 'VANTA:PRI-14';
    case PRI_15 = 'VANTA:PRI-15';
    case PRI_16 = 'VANTA:PRI-16';
    case PRI_17 = 'VANTA:PRI-17';
    case PRI_2 = 'VANTA:PRI-2';
    case PRI_3 = 'VANTA:PRI-3';
    case PRI_4 = 'VANTA:PRI-4';
    case PRI_5 = 'VANTA:PRI-5';
    case PRI_6 = 'VANTA:PRI-6';
    case PRI_7 = 'VANTA:PRI-7';
    case PRI_8 = 'VANTA:PRI-8';
    case PRI_9 = 'VANTA:PRI-9';
    case PRM_1 = 'VANTA:PRM-1';
    case PRM_2 = 'VANTA:PRM-2';
    case PRM_3 = 'VANTA:PRM-3';
    case RSK_1 = 'VANTA:RSK-1';
    case RSK_2 = 'VANTA:RSK-2';
    case RSK_3 = 'VANTA:RSK-3';
    case SAT_1 = 'VANTA:SAT-1';
    case TDA_1 = 'VANTA:TDA-1';
    case TDA_2 = 'VANTA:TDA-2';
    case TDA_3 = 'VANTA:TDA-3';
    case TDA_4 = 'VANTA:TDA-4';
    case TPM_1 = 'VANTA:TPM-1';
    case TPM_2 = 'VANTA:TPM-2';
    case VPM_1 = 'VANTA:VPM-1';
    case VPM_2 = 'VANTA:VPM-2';

    public function id(): string
    {
        return $this->value;
    }

    public function source(): string
    {
        return 'Vanta';
    }

    public function externalId(): string
    {
        return str_replace('VANTA:', '', $this->value);
    }

    public function slug(): string
    {
        return match ($this) {
            self::AST_1 => 'asset-disposal-procedures-utilized',
            self::AST_2 => 'data-retention-procedures-established',
            self::AST_3 => 'production-inventory-maintained',
            self::BCD_1 => 'continuity-and-disaster-recovery-plans-established',
            self::BCD_2 => 'continuity-disaster-recovery-plans-tested',
            self::BCD_3 => 'cybersecurity-insurance-maintained',
            self::BCD_4 => 'database-replication-utilized',
            self::BCD_5 => 'production-data-backups-conducted',
            self::BCD_6 => 'system-multiple-availability-zones',
            self::CAP_1 => 'system-capacity-reviewed',
            self::CFG_1 => 'configuration-management-system-established',
            self::CHG_1 => 'change-management-procedures',
            self::CHG_2 => 'changes-approval-required',
            self::CHG_3 => 'development-lifecycle-established',
            self::CPL_1 => 'system-description',
            self::CPL_2 => 'whistleblower-policy-established',
            self::CRY_1 => 'access-datastores-ssh',
            self::CRY_2 => 'access-encryption-keys',
            self::CRY_3 => 'assets-portable-media-encrypted',
            self::CRY_4 => 'data-encrypted',
            self::CRY_5 => 'unique-account-authentication-enforced',
            self::DCH_1 => 'customer-data-deleted-upon-leave',
            self::DCH_10 => 'privacy-sensitive-data-disposal',
            self::DCH_11 => 'production-data-segmented',
            self::DCH_2 => 'customer-data-retained',
            self::DCH_3 => 'customer-transaction-modifications-restricted',
            self::DCH_4 => 'customer-transactions-portal-available',
            self::DCH_5 => 'data-classification-policy',
            self::DCH_6 => 'data-deletion-requests-handled',
            self::DCH_7 => 'personal-information-changes-communicated',
            self::DCH_8 => 'privacy-identity-verification',
            self::DCH_9 => 'privacy-inquiries-handled',
            self::END_1 => 'assets-anti-malware',
            self::GOV_1 => 'board-of-directors-briefing',
            self::GOV_10 => 'role-responsibilities-specified',
            self::GOV_11 => 'security-policies-established-reviewed',
            self::GOV_12 => 'support-system-available',
            self::GOV_13 => 'system-changes-communicated',
            self::GOV_2 => 'board-of-directors-charter',
            self::GOV_3 => 'board-of-directors-expertise',
            self::GOV_4 => 'board-of-directors-meeting',
            self::GOV_5 => 'data-backup-procedures',
            self::GOV_6 => 'external-service-impact-notifications',
            self::GOV_7 => 'management-roles-responsibilities-defined',
            self::GOV_8 => 'organization-structure-documented',
            self::GOV_9 => 'processing-alerts-available',
            self::HRS_1 => 'background-checks-performed',
            self::HRS_2 => 'code-of-conduct-acknowledged-contractors',
            self::HRS_3 => 'code-of-conduct-acknowledged-employees',
            self::HRS_4 => 'confidentiality-agreement-acknowledged-contractors',
            self::HRS_5 => 'confidentiality-agreement-acknowledged-employees',
            self::HRS_6 => 'performance-evaluations-conducted',
            self::IAC_1 => 'access-application-restricted',
            self::IAC_10 => 'access-ssh-required',
            self::IAC_11 => 'policies-password-complexity',
            self::IAC_12 => 'remote-access-mfa-enforced',
            self::IAC_13 => 'remote-access-vpn-enforced',
            self::IAC_2 => 'access-control-procedures',
            self::IAC_3 => 'access-database-restricted-users',
            self::IAC_4 => 'access-firewalls',
            self::IAC_5 => 'access-operating-system-restricted',
            self::IAC_6 => 'access-production-network-restricted',
            self::IAC_7 => 'access-reviews',
            self::IAC_8 => 'access-revoked-termination',
            self::IAC_9 => 'access-role-based',
            self::IAO_1 => 'control-self-assessments-conducted',
            self::IAO_2 => 'penetration-testing',
            self::IRO_1 => 'incident-response-plan-tested',
            self::IRO_2 => 'incident-response-policies-established',
            self::IRO_3 => 'policies-incident-management',
            self::IRO_4 => 'privacy-data-sharing',
            self::MDM_1 => 'MDM-system-utilized',
            self::MON_1 => 'intrusion-detection-system',
            self::MON_2 => 'log-management-utilized',
            self::MON_3 => 'system-data-input-monitoring',
            self::MON_4 => 'system-threshold-monitoring',
            self::NET_1 => 'data-encrypted-in-transit',
            self::NET_2 => 'infra-network-segregation',
            self::NET_3 => 'network-firewalls-reviewed',
            self::NET_4 => 'network-firewalls-utilized',
            self::NET_5 => 'system-network-hardening',
            self::OPS_1 => 'policies-incident-monitoring',
            self::PES_1 => 'access-physical-datacenter',
            self::PES_2 => 'access-physical-review',
            self::PES_3 => 'access-physical-visitors',
            self::PES_4 => 'environmental-monitoring-devices-implemented',
            self::PES_5 => 'environmental-security-inspected-annually',
            self::PRI_1 => 'legal-personal-information-tracked',
            self::PRI_10 => 'privacy-individual-consent-obtained',
            self::PRI_11 => 'privacy-new-information-purpose-consent',
            self::PRI_12 => 'privacy-opt-out',
            self::PRI_13 => 'privacy-policies-personal-information-use-reviewed',
            self::PRI_14 => 'privacy-policy-available',
            self::PRI_15 => 'privacy-policy-established',
            self::PRI_16 => 'privacy-policy-reviewed',
            self::PRI_17 => 'third-party-privacy-documentation-reviewed',
            self::PRI_2 => 'personal-data-updates',
            self::PRI_3 => 'personal-information-collection-changes-communicated',
            self::PRI_4 => 'personal-information-collection-reviewed',
            self::PRI_5 => 'personal-information-reliability-verified',
            self::PRI_6 => 'policies-privacy-policy',
            self::PRI_7 => 'privacy-complaints-procedures',
            self::PRI_8 => 'privacy-data-retained',
            self::PRI_9 => 'privacy-explicity-consent-obtained',
            self::PRM_1 => 'commitments-externally-communicated',
            self::PRM_2 => 'external-support-resources',
            self::PRM_3 => 'service-description-communicated',
            self::RSK_1 => 'risk-assessment-objectives',
            self::RSK_2 => 'risk-assessment-performed',
            self::RSK_3 => 'risk-assessment-program',
            self::SAT_1 => 'security-awareness-training-completed',
            self::TDA_1 => 'policies-passwords-enforced',
            self::TDA_2 => 'processing-issues-automatically-alerted',
            self::TDA_3 => 'system-activity-logged',
            self::TDA_4 => 'system-customer-input-validation',
            self::TPM_1 => 'third-party-agreements',
            self::TPM_2 => 'vendor-management-program-established',
            self::VPM_1 => 'support-infra-patched',
            self::VPM_2 => 'vulnerability-scans-conducted',
        };
    }

    public function title(): string
    {
        return match ($this) {
            self::AST_1 => 'Asset disposal procedures utilized',
            self::AST_2 => 'Data retention procedures established',
            self::AST_3 => 'Production inventory maintained',
            self::BCD_1 => 'Continuity and Disaster Recovery plans established',
            self::BCD_2 => 'Continuity and Disaster Recovery plans tested',
            self::BCD_3 => 'Cybersecurity insurance maintained',
            self::BCD_4 => 'Database Replication Utilized',
            self::BCD_5 => 'Production Data Backups Conducted',
            self::BCD_6 => 'System Multiple Availability Zones',
            self::CAP_1 => 'System Capacity Reviewed',
            self::CFG_1 => 'Configuration management system established',
            self::CHG_1 => 'Change management procedures enforced',
            self::CHG_2 => 'Production deployment access restricted',
            self::CHG_3 => 'Development lifecycle established',
            self::CPL_1 => 'SOC 2 - System Description',
            self::CPL_2 => 'Whistleblower policy established',
            self::CRY_1 => 'Unique production database authentication enforced',
            self::CRY_2 => 'Encryption key access restricted',
            self::CRY_3 => 'Assets Portable Media Encrypted',
            self::CRY_4 => 'Data encryption utilized',
            self::CRY_5 => 'Unique account authentication enforced',
            self::DCH_1 => 'Customer data deleted upon leaving',
            self::DCH_10 => 'Privacy Sensitive Data Disposal',
            self::DCH_11 => 'Production Data Segmented',
            self::DCH_2 => 'Customer Data Retained',
            self::DCH_3 => 'Customer Transaction Modifications Restricted',
            self::DCH_4 => 'Customer Transactions Portal Available',
            self::DCH_5 => 'Data classification policy established',
            self::DCH_6 => 'Data Deletion Requests Handled',
            self::DCH_7 => 'Personal Information Changes Communicated',
            self::DCH_8 => 'Privacy Identity Verification',
            self::DCH_9 => 'Privacy Inquiries Handled',
            self::END_1 => 'Anti-malware technology utilized',
            self::GOV_1 => 'Board oversight briefings conducted',
            self::GOV_10 => 'Roles and responsibilities specified',
            self::GOV_11 => 'Security policies established and reviewed',
            self::GOV_12 => 'Support system available',
            self::GOV_13 => 'System changes communicated',
            self::GOV_2 => 'Board charter documented',
            self::GOV_3 => 'Board expertise developed',
            self::GOV_4 => 'Board meetings conducted',
            self::GOV_5 => 'Backup processes established',
            self::GOV_6 => 'System changes externally communicated',
            self::GOV_7 => 'Management roles and responsibilities defined',
            self::GOV_8 => 'Organization structure documented',
            self::GOV_9 => 'Processing Alerts Available',
            self::HRS_1 => 'Employee background checks performed',
            self::HRS_2 => 'Code of Conduct acknowledged by contractors',
            self::HRS_3 => 'Code of Conduct acknowledged by employees and enforced',
            self::HRS_4 => 'Confidentiality Agreement acknowledged by contractors',
            self::HRS_5 => 'Confidentiality Agreement acknowledged by employees',
            self::HRS_6 => 'Performance evaluations conducted',
            self::IAC_1 => 'Production application access restricted',
            self::IAC_10 => 'Unique network system authentication enforced',
            self::IAC_11 => 'Password policy enforced',
            self::IAC_12 => 'Remote access MFA enforced',
            self::IAC_13 => 'Remote access encrypted enforced',
            self::IAC_2 => 'Access control procedures established',
            self::IAC_3 => 'Production database access restricted',
            self::IAC_4 => 'Firewall access restricted',
            self::IAC_5 => 'Production OS access restricted',
            self::IAC_6 => 'Production network access restricted',
            self::IAC_7 => 'Access reviews conducted',
            self::IAC_8 => 'Access revoked upon termination',
            self::IAC_9 => 'Access requests required',
            self::IAO_1 => 'Control self-assessments conducted',
            self::IAO_2 => 'Penetration testing performed',
            self::IRO_1 => 'Incident response plan tested',
            self::IRO_2 => 'Incident response policies established',
            self::IRO_3 => 'Incident management procedures followed',
            self::IRO_4 => 'Privacy Data Sharing',
            self::MDM_1 => 'MDM system utilized',
            self::MON_1 => 'Intrusion detection system utilized',
            self::MON_2 => 'Log management utilized',
            self::MON_3 => 'System Data Input Monitoring',
            self::MON_4 => 'Infrastructure performance monitored',
            self::NET_1 => 'Data transmission encrypted',
            self::NET_2 => 'Network segmentation implemented',
            self::NET_3 => 'Network firewalls reviewed',
            self::NET_4 => 'Network firewalls utilized',
            self::NET_5 => 'Network and system hardening standards maintained',
            self::OPS_1 => 'Vulnerability and system monitoring procedures established',
            self::PES_1 => 'Access Physical Datacenter',
            self::PES_2 => 'Access Physical Review',
            self::PES_3 => 'Access Physical Visitors',
            self::PES_4 => 'Environmental Monitoring Devices Implemented',
            self::PES_5 => 'Environmental Security Inspected Annually',
            self::PRI_1 => 'Legal Personal Information Tracked',
            self::PRI_10 => 'Privacy Individual Consent Obtained',
            self::PRI_11 => 'Privacy New Information Purpose Consent',
            self::PRI_12 => 'Privacy Opt Out',
            self::PRI_13 => 'Privacy Policies Personal Information Use Reviewed',
            self::PRI_14 => 'Privacy Policy Available',
            self::PRI_15 => 'Privacy Policy Established',
            self::PRI_16 => 'Privacy Policy Reviewed',
            self::PRI_17 => 'Third Party Privacy Documentation Reviewed',
            self::PRI_2 => 'Personal Data Updates',
            self::PRI_3 => 'Personal Information Collection Changes Communicated',
            self::PRI_4 => 'Personal Information Collection Reviewed',
            self::PRI_5 => 'Personal Information Reliability Verified',
            self::PRI_6 => 'Policies Privacy Policy',
            self::PRI_7 => 'Privacy Complaints Procedures',
            self::PRI_8 => 'Privacy Data Retained',
            self::PRI_9 => 'Privacy Explicity Consent Obtained',
            self::PRM_1 => 'Company commitments externally communicated',
            self::PRM_2 => 'External support resources available',
            self::PRM_3 => 'Service description communicated',
            self::RSK_1 => 'Risk assessment objectives specified',
            self::RSK_2 => 'Risks assessments performed',
            self::RSK_3 => 'Risk management program established',
            self::SAT_1 => 'Security awareness training implemented',
            self::TDA_1 => 'Policies Passwords Enforced',
            self::TDA_2 => 'Processing Issues Automatically Alerted',
            self::TDA_3 => 'System Activity Logged',
            self::TDA_4 => 'System Customer Input Validation',
            self::TPM_1 => 'Third-party agreements established',
            self::TPM_2 => 'Vendor management program established',
            self::VPM_1 => 'Service infrastructure maintained',
            self::VPM_2 => 'Vulnerabilities scanned and remediated',
        };
    }

    public function description(): ?string
    {
        return match ($this) {
            self::AST_1 => 'The company has electronic media containing confidential information purged or destroyed in accordance with best practices, and certificates of destruction are issued for each device destroyed.',
            self::AST_2 => 'The company has formal retention and disposal procedures in place to guide the secure retention and disposal of company and customer data.',
            self::AST_3 => 'The company maintains a formal inventory of production system assets.',
            self::BCD_1 => 'The company has Business Continuity and Disaster Recovery Plans in place that outline communication plans in order to maintain information security continuity in the event of the unavailability of key personnel.',
            self::BCD_2 => 'The company has a documented Business Continuity/Disaster Recovery (BC/DR) plan and tests it at least annually.',
            self::BCD_3 => 'The company maintains cybersecurity insurance to mitigate the financial impact of business disruptions.',
            self::BCD_4 => null,
            self::BCD_5 => null,
            self::BCD_6 => null,
            self::CAP_1 => null,
            self::CFG_1 => 'The company has a configuration management procedure in place to ensure that system configurations are deployed consistently throughout the environment.',
            self::CHG_1 => 'The company requires changes to software and infrastructure components of the service to be authorized, formally documented, tested, reviewed, and approved prior to being implemented in the production environment.',
            self::CHG_2 => 'The company restricts access to migrate changes to production to authorized personnel.',
            self::CHG_3 => 'The company has a formal systems development life cycle (SDLC) methodology in place that governs the development, acquisition, implementation, changes (including emergency changes), and maintenance of information systems and related technology requirements.',
            self::CPL_1 => 'Complete a description of your system for Section III of the audit report',
            self::CPL_2 => 'The company has established a formalized whistleblower policy, and an anonymous communication channel is in place for users to report potential issues or fraud concerns.',
            self::CRY_1 => 'The company requires authentication to production datastores to use authorized secure authentication mechanisms, such as unique SSH key.',
            self::CRY_2 => 'The company restricts privileged access to encryption keys to authorized users with a business need.',
            self::CRY_3 => null,
            self::CRY_4 => 'The company\'s datastores housing sensitive customer data are encrypted at rest.',
            self::CRY_5 => 'The company requires authentication to systems and applications to use unique username and password or authorized Secure Socket Shell (SSH) keys.',
            self::DCH_1 => 'The company purges or removes customer data containing confidential information from the application environment, in accordance with best practices, when customers leave the service.',
            self::DCH_10 => null,
            self::DCH_11 => null,
            self::DCH_2 => null,
            self::DCH_3 => null,
            self::DCH_4 => null,
            self::DCH_5 => 'The company has a data classification policy in place to help ensure that confidential data is properly secured and restricted to authorized personnel.',
            self::DCH_6 => null,
            self::DCH_7 => null,
            self::DCH_8 => null,
            self::DCH_9 => null,
            self::END_1 => 'The company deploys anti-malware technology to environments commonly susceptible to malicious attacks and configures this to be updated routinely, logged, and installed on all relevant systems.',
            self::GOV_1 => 'The company\'s board of directors or a relevant subcommittee is briefed by senior management at least annually on the state of the company\'s cybersecurity and privacy risk. The board provides feedback and direction to management as needed.',
            self::GOV_10 => 'Roles and responsibilities for the design, development, implementation, operation, maintenance, and monitoring of information security controls are formally assigned in job descriptions and/or the Roles and Responsibilities policy.',
            self::GOV_11 => 'The company\'s information security policies and procedures are documented and reviewed at least annually.',
            self::GOV_12 => 'The company has an external-facing support system in place that allows users to report system information on failures, incidents, concerns, and other complaints to appropriate personnel.',
            self::GOV_13 => 'The company communicates system changes to authorized internal users.',
            self::GOV_2 => 'The company\'s board of directors has a documented charter that outlines its oversight responsibilities for internal control.',
            self::GOV_3 => 'The company\'s board members have sufficient expertise to oversee management\'s ability to design, implement and operate information security controls. The board engages third-party information security experts and consultants as needed.',
            self::GOV_4 => 'The company\'s board of directors meets at least annually and maintains formal meeting minutes. The board includes directors that are independent of the company.',
            self::GOV_5 => 'The company\'s data backup policy documents requirements for backup and recovery of customer data.',
            self::GOV_6 => 'The company notifies customers of critical system changes that may affect their processing.',
            self::GOV_7 => 'The company management has established defined roles and responsibilities to oversee the design and implementation of information security controls.',
            self::GOV_8 => 'The company maintains an organizational chart that describes the organizational structure and reporting lines.',
            self::GOV_9 => null,
            self::HRS_1 => 'The company performs background checks on new employees.',
            self::HRS_2 => 'The company requires contractor agreements to include a code of conduct or reference to the company code of conduct.',
            self::HRS_3 => 'The company requires employees to acknowledge a code of conduct at the time of hire. Employees who violate the code of conduct are subject to disciplinary actions in accordance with a disciplinary policy.',
            self::HRS_4 => 'The company requires contractors to sign a confidentiality agreement at the time of engagement.',
            self::HRS_5 => 'The company requires employees to sign a confidentiality agreement during onboarding.',
            self::HRS_6 => 'The company managers are required to complete performance evaluations for direct reports at least annually.',
            self::IAC_1 => 'System access restricted to authorized access only',
            self::IAC_10 => 'The company requires authentication to the "production network" to use unique usernames and passwords or authorized Secure Socket Shell (SSH) keys.',
            self::IAC_11 => 'The company requires passwords for in-scope system components to be configured according to the company\'s policy.',
            self::IAC_12 => 'The company\'s production systems can only be remotely accessed by authorized employees possessing a valid multi-factor authentication (MFA) method.',
            self::IAC_13 => 'The company\'s production systems can only be remotely accessed by authorized employees via an approved encrypted connection.',
            self::IAC_2 => 'The company\'s access control policy documents the requirements for the following access control functions: \n\n- adding new users;\n\n- modifying users; and/or \n\n- removing an existing user\'s access.',
            self::IAC_3 => 'The company restricts privileged access to databases to authorized users with a business need.',
            self::IAC_4 => 'The company restricts privileged access to the firewall to authorized users with a business need.',
            self::IAC_5 => 'The company restricts privileged access to the operating system to authorized users with a business need.',
            self::IAC_6 => 'The company restricts privileged access to the production network to authorized users with a business need.',
            self::IAC_7 => 'The company conducts access reviews at least quarterly for the in-scope system components to help ensure that access is restricted appropriately. Required changes are tracked to completion.',
            self::IAC_8 => 'The company completes termination checklists to ensure that access is revoked for terminated employees within SLAs.',
            self::IAC_9 => 'The company ensures that user access to in-scope system components is based on job role and function or requires a documented access request form and manager approval prior to access being provisioned.',
            self::IAO_1 => 'The company performs control self-assessments at least annually to gain assurance that controls are in place and operating effectively. Corrective actions are taken based on relevant findings. If the company has committed to an SLA for a finding, the corrective action is completed within that SLA.',
            self::IAO_2 => 'The company\'s penetration testing is performed at least annually. A remediation plan is developed and changes are implemented to remediate vulnerabilities in accordance with SLAs.',
            self::IRO_1 => 'The company tests their incident response plan at least annually.',
            self::IRO_2 => 'The company has security and privacy incident response policies and procedures that are documented and communicated to authorized users.',
            self::IRO_3 => 'The company\'s security and privacy incidents are logged, tracked, resolved, and communicated to affected or relevant parties by management according to the company\'s security incident response policy and procedures.',
            self::IRO_4 => null,
            self::MDM_1 => 'The company has a mobile device management (MDM) system in place to centrally manage mobile devices supporting the service.',
            self::MON_1 => 'The company uses an intrusion detection system to provide continuous monitoring of the company\'s network and early detection of potential security breaches.',
            self::MON_2 => 'The company utilizes a log management tool to identify events that may have a potential impact on the company\'s ability to achieve its security objectives.',
            self::MON_3 => null,
            self::MON_4 => 'An infrastructure monitoring tool is utilized to monitor systems, infrastructure, and performance and generates alerts when specific predefined thresholds are met.',
            self::NET_1 => 'The company uses secure data transmission protocols to encrypt confidential and sensitive data when transmitted over public networks.',
            self::NET_2 => 'The company\'s network is segmented to prevent unauthorized access to customer data.',
            self::NET_3 => 'The company reviews its firewall rulesets at least annually. Required changes are tracked to completion.',
            self::NET_4 => 'The company uses firewalls and configures them to prevent unauthorized access.',
            self::NET_5 => 'The company\'s network and system hardening standards are documented, based on industry best practices, and reviewed at least annually.',
            self::OPS_1 => 'The company\'s formal policies outline the requirements for the following functions related to IT / Engineering: \n\n- vulnerability management;\n\n- system monitoring.',
            self::PES_1 => null,
            self::PES_2 => null,
            self::PES_3 => null,
            self::PES_4 => null,
            self::PES_5 => null,
            self::PRI_1 => null,
            self::PRI_10 => null,
            self::PRI_11 => null,
            self::PRI_12 => null,
            self::PRI_13 => null,
            self::PRI_14 => null,
            self::PRI_15 => null,
            self::PRI_16 => null,
            self::PRI_17 => null,
            self::PRI_2 => null,
            self::PRI_3 => null,
            self::PRI_4 => null,
            self::PRI_5 => null,
            self::PRI_6 => null,
            self::PRI_7 => null,
            self::PRI_8 => null,
            self::PRI_9 => null,
            self::PRM_1 => 'The company\'s security commitments are communicated to customers in Master Service Agreements (MSA) or Terms of Service (TOS).',
            self::PRM_2 => 'The company provides guidelines and technical support resources relating to system operations to customers.',
            self::PRM_3 => 'The company provides a description of its products and services to internal and external users.',
            self::RSK_1 => 'The company specifies its objectives to enable the identification and assessment of risk related to the objectives.',
            self::RSK_2 => 'The company\'s risk assessments are performed at least annually. As part of this process, threats and changes (environmental, regulatory, and technological) to service commitments are identified and the risks are formally assessed. The risk assessment includes a consideration of the potential for fraud and how fraud may impact the achievement of objectives.',
            self::RSK_3 => 'The company has a documented risk management program in place that includes guidance on the identification of potential threats, rating the significance of the risks associated with the identified threats, and mitigation strategies for those risks.',
            self::SAT_1 => 'The company requires employees to complete security awareness training within thirty days of hire and at least annually thereafter.',
            self::TDA_1 => null,
            self::TDA_2 => null,
            self::TDA_3 => null,
            self::TDA_4 => null,
            self::TPM_1 => 'The company has written agreements in place with vendors and related third-parties. These agreements include confidentiality and privacy commitments applicable to that entity.',
            self::TPM_2 => 'The company has a vendor management program in place. Components of this program include:\n\n- critical third-party vendor inventory;\n\n- vendor\'s security and privacy requirements; and\n\n- review of critical third-party vendors at least annually.',
            self::VPM_1 => 'The company has infrastructure supporting the service patched as a part of routine maintenance and as a result of identified vulnerabilities to help ensure that servers supporting the service are hardened against security threats.',
            self::VPM_2 => 'Host-based vulnerability scans are performed at least quarterly on all external-facing systems. Critical and high vulnerabilities are tracked to remediation.',
        };
    }

    public function domains(): array
    {
        return match ($this) {
            self::AST_1 => ['ASSET_MANAGEMENT'],
            self::AST_2 => ['ASSET_MANAGEMENT'],
            self::AST_3 => ['ASSET_MANAGEMENT'],
            self::BCD_1 => ['BUSINESS_CONTINUITY_&_DISASTER_RECOVERY'],
            self::BCD_2 => ['BUSINESS_CONTINUITY_&_DISASTER_RECOVERY'],
            self::BCD_3 => ['BUSINESS_CONTINUITY_&_DISASTER_RECOVERY'],
            self::BCD_4 => [],
            self::BCD_5 => [],
            self::BCD_6 => [],
            self::CAP_1 => [],
            self::CFG_1 => ['CONFIGURATION_MANAGEMENT'],
            self::CHG_1 => ['CHANGE_MANAGEMENT'],
            self::CHG_2 => ['CHANGE_MANAGEMENT'],
            self::CHG_3 => ['CHANGE_MANAGEMENT'],
            self::CPL_1 => ['COMPLIANCE'],
            self::CPL_2 => ['COMPLIANCE'],
            self::CRY_1 => ['CRYPTOGRAPHIC_PROTECTIONS'],
            self::CRY_2 => ['CRYPTOGRAPHIC_PROTECTIONS'],
            self::CRY_3 => [],
            self::CRY_4 => ['CRYPTOGRAPHIC_PROTECTIONS'],
            self::CRY_5 => ['CRYPTOGRAPHIC_PROTECTIONS'],
            self::DCH_1 => ['DATA_CLASSIFICATION_&_HANDLING'],
            self::DCH_10 => [],
            self::DCH_11 => [],
            self::DCH_2 => [],
            self::DCH_3 => [],
            self::DCH_4 => [],
            self::DCH_5 => ['DATA_CLASSIFICATION_&_HANDLING'],
            self::DCH_6 => [],
            self::DCH_7 => [],
            self::DCH_8 => [],
            self::DCH_9 => [],
            self::END_1 => ['ENDPOINT_SECURITY'],
            self::GOV_1 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_10 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_11 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_12 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_13 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_2 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_3 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_4 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_5 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_6 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_7 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_8 => ['SECURITY_&_PRIVACY_GOVERNANCE'],
            self::GOV_9 => [],
            self::HRS_1 => ['HUMAN_RESOURCES_SECURITY'],
            self::HRS_2 => ['HUMAN_RESOURCES_SECURITY'],
            self::HRS_3 => ['HUMAN_RESOURCES_SECURITY'],
            self::HRS_4 => ['HUMAN_RESOURCES_SECURITY'],
            self::HRS_5 => ['HUMAN_RESOURCES_SECURITY'],
            self::HRS_6 => ['HUMAN_RESOURCES_SECURITY'],
            self::IAC_1 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_10 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_11 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_12 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_13 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_2 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_3 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_4 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_5 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_6 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_7 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_8 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAC_9 => ['IDENTIFICATION_&_AUTHENTICATION'],
            self::IAO_1 => ['INFORMATION_ASSURANCE'],
            self::IAO_2 => ['INFORMATION_ASSURANCE'],
            self::IRO_1 => ['INCIDENT_RESPONSE'],
            self::IRO_2 => ['INCIDENT_RESPONSE'],
            self::IRO_3 => ['INCIDENT_RESPONSE'],
            self::IRO_4 => [],
            self::MDM_1 => ['MOBILE_DEVICE_MANAGEMENT'],
            self::MON_1 => ['CONTINUOUS_MONITORING'],
            self::MON_2 => ['CONTINUOUS_MONITORING'],
            self::MON_3 => [],
            self::MON_4 => ['CONTINUOUS_MONITORING'],
            self::NET_1 => ['NETWORK SECURITY'],
            self::NET_2 => ['NETWORK SECURITY'],
            self::NET_3 => ['NETWORK SECURITY'],
            self::NET_4 => ['NETWORK SECURITY'],
            self::NET_5 => ['NETWORK SECURITY'],
            self::OPS_1 => ['SECURITY_OPERATIONS'],
            self::PES_1 => [],
            self::PES_2 => [],
            self::PES_3 => [],
            self::PES_4 => [],
            self::PES_5 => [],
            self::PRI_1 => [],
            self::PRI_10 => [],
            self::PRI_11 => [],
            self::PRI_12 => [],
            self::PRI_13 => [],
            self::PRI_14 => [],
            self::PRI_15 => [],
            self::PRI_16 => [],
            self::PRI_17 => [],
            self::PRI_2 => [],
            self::PRI_3 => [],
            self::PRI_4 => [],
            self::PRI_5 => [],
            self::PRI_6 => [],
            self::PRI_7 => [],
            self::PRI_8 => [],
            self::PRI_9 => [],
            self::PRM_1 => ['PROJECT_&_RESOURCE MANAGEMENT'],
            self::PRM_2 => ['PROJECT_&_RESOURCE MANAGEMENT'],
            self::PRM_3 => ['PROJECT_&_RESOURCE MANAGEMENT'],
            self::RSK_1 => ['RISK_MANAGEMENT'],
            self::RSK_2 => ['RISK_MANAGEMENT'],
            self::RSK_3 => ['RISK_MANAGEMENT'],
            self::SAT_1 => ['SECURITY_AWARENESS_&_TRAINING'],
            self::TDA_1 => [],
            self::TDA_2 => [],
            self::TDA_3 => [],
            self::TDA_4 => [],
            self::TPM_1 => ['THIRD-PARTY_MANAGEMENT'],
            self::TPM_2 => ['THIRD-PARTY_MANAGEMENT'],
            self::VPM_1 => ['VULNERABILITY_&_PATCH_MANAGEMENT'],
            self::VPM_2 => ['VULNERABILITY_&_PATCH_MANAGEMENT'],
        };
    }
}
