name: Generate Compliance Data

on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 8 * * 1'

jobs:
  generate-compliance-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, json
          tools: composer

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Generate Compliance Data
        run: |
          php vendor/bin/testbench security:generate-vanta-data --control-enum-output=src/Controls/ComplianceControl.php

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update generated compliance data"
          file_pattern: "resources/frameworks/vanta/data/*.php src/Controls/ComplianceControl.php"
